prometheus:
  url: http://localhost:9090

train:
  path: ./tmp/train

  start_at: 2024-10-04T07:25:00Z
  end_at: 2024-10-04T07:35:00Z

  features:
    # cpu_time: sum(rate(kepler_process_bpf_cpu_time_ms_total{job="vm"}[20s]))
    node_cpu_time: sum( rate(node_cpu_seconds_total{job="vm-node-exporter", mode=~"user"}[20s])) * 1000
    #page_cache_hits: sum(rate(kepler_process_bpf_page_cache_hit_total{job="vm"}[5s]))
    cpus: 2

  learn: sum(rate(kepler_vm_package_joules_total{job="metal"}[20s]))

  models:
    xgboost:
    linear:
    polynomial:
      degree: 2
